### ISSUE TITLE
Getting CouchbaseException while connecting to cluster after entering the streamlit password

### ISSUE THREAD

**Issue by CosmicSaaurabh** [couchbase-examples/rag-demo#9]
Unable to connect to couchbase cluster after running this command: streamlit run chat_with_pdf.py, fails with CouchbaseException operation aborted. 

```
streamlit run chat_with_pdf.py

      👋 Welcome to Streamlit!

      If you’d like to receive helpful onboarding emails, news, offers, promotions,
      and the occasional swag, please enter your email address below. Otherwise,
      leave this field blank.

      Email:  saurabh.mishra@couchbase.com

  You can find our privacy policy at https://streamlit.io/privacy-policy

  Summary:
  - This open source library collects usage statistics.
  - We cannot see and do not store information contained inside Streamlit apps,
    such as text, charts, images, etc.
  - Telemetry data is stored in servers in the United States.
  - If you'd like to opt out, add the following to ~/.streamlit/config.toml,
    creating that file if necessary:

    [browser]
    gatherUsageStats = false


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.16.1.84:8501

  For better performance, install the Watchdog module:

  $ xcode-select --install
  $ pip install watchdog
            
2024-04-30 12:47:42.948 Uncaught app exception
Traceback (most recent call last):
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo/chat_with_pdf.py", line 133, in <module>
    cluster = connect_to_couchbase(DB_CONN_STR, DB_USERNAME, DB_PASSWORD)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 168, in wrapper
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 197, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 224, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 280, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo/chat_with_pdf.py", line 76, in connect_to_couchbase
    cluster = Cluster(connect_string, options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/couchbase/cluster.py", line 101, in __init__
    self._connect()
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/couchbase/logic/wrappers.py", line 98, in wrapped_fn
    raise e
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/couchbase/logic/wrappers.py", line 82, in wrapped_fn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/couchbase/cluster.py", line 107, in _connect
    raise ErrorMapper.build_exception(ret)
couchbase.exceptions.CouchbaseException: <ec=89, category=asio.system, message=Operation aborted., C Source=/private/var/folders/7w/ftplgyn52g5c95607zxkwp4m0000gq/T/pip-install-fflpx023/couchbase_9f7fcf8031554df889893a7a0d80ae91/src/connection.cxx:202>
```

`Running on python version 3.12.2,`

```
pip3 freeze
aiohttp==3.9.5
aiosignal==1.3.1
altair==5.3.0
annotated-types==0.6.0
anyio==4.3.0
attrs==23.2.0
blinker==1.8.1
cachetools==5.3.3
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
couchbase==4.2.1
dataclasses-json==0.6.5
distro==1.9.0
frozenlist==1.4.1
gitdb==4.0.11
GitPython==3.1.43
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
Jinja2==3.1.3
jsonpatch==1.33
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
langchain==0.1.16
langchain-community==0.0.34
langchain-core==0.1.46
langchain-openai==0.1.3
langchain-text-splitters==0.0.1
langsmith==0.1.52
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.21.1
mdurl==0.1.2
multidict==6.0.5
mypy-extensions==1.0.0
numpy==1.26.4
openai==1.24.0
orjson==3.10.1
packaging==23.2
pandas==2.2.2
pillow==10.3.0
protobuf==4.25.3
pyarrow==16.0.0
pydantic==2.7.1
pydantic_core==2.18.2
pydeck==0.9.0
Pygments==2.17.2
pypdf==4.2.0
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
referencing==0.35.0
regex==2024.4.28
requests==2.31.0
rich==13.7.1
rpds-py==0.18.0
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
SQLAlchemy==2.0.29
streamlit==1.33.0
tenacity==8.2.3
tiktoken==0.6.0
toml==0.10.2
toolz==0.12.1
tornado==6.4
tqdm==4.66.2
typing-inspect==0.9.0
typing_extensions==4.11.0
tzdata==2024.1
urllib3==2.2.1
yarl==1.9.4
```

**Comment by nithishr** [comment]
@CosmicSaaurabh It looks like a Couchbase SDK error. 
Are the cluster credentials correct?
Can you share the debug logs while running the app?
You should be able to do it by [setting](PYCBC_LOG_LEVEL) the environment variable `PYCBC_LOG_LEVEL` 

$export PYCBC_LOG_LEVEL=debug 

Also, note that Python 3.12 is not officially [supported](https://docs.couchbase.com/python-sdk/current/project-docs/compatibility.html#python-version-compatibility) by the Couchbase SDK.

**Comment by CosmicSaaurabh** [comment]
Here is log in debug level

` 58ms [debu] [42695,2096273] Selected nameserver: "10.100.189.12" from "/etc/resolv.conf"
[2024-04-30 17:08:33.921]    2ms [debu] [42695,2096273] open cluster, id: "438f72-01e3-6a4c-3f84-893067d315df66", core version: "1.0.0+", {"bootstrap_nodes":[{"hostname":"cb.wrr-19l-u8l1lyvi.sandbox.nonprod-project-avengers.com","port":"11207"}],"options":{"analytics_timeout":"75000ms","bootstrap_timeout":"10000ms","config_idle_redial_timeout":"300000ms","config_poll_floor":"50ms","config_poll_interval":"2500ms","connect_timeout":"2000ms","disable_mozilla_ca_certificates":false,"dns_config":{"nameserver":"10.100.189.12","port":53,"timeout":"500ms"},"dump_configuration":false,"enable_clustermap_notification":true,"enable_compression":true,"enable_dns_srv":true,"enable_metrics":true,"enable_mutation_tokens":true,"enable_tcp_keep_alive":true,"enable_tls":true,"enable_tracing":true,"enable_unordered_execution":true,"idle_http_connection_timeout":"1000ms","key_value_durable_timeout":"10000ms","key_value_timeout":"2500ms","management_timeout":"75000ms","max_http_connections":0,"metrics_options":{"emit_interval":"600000ms"},"network":"auto","query_timeout":"75000ms","resolve_timeout":"2000ms","search_timeout":"75000ms","show_queries":false,"tcp_keep_alive_interval":"60000ms","tls_verify":"peer","tracing_options":{"analytics_threshold":"1000ms","key_value_threshold":"500ms","management_threshold":"1000ms","orphaned_emit_interval":"10000ms","orphaned_sample_size":64,"query_threshold":"1000ms","search_threshold":"1000ms","threshold_emit_interval":"10000ms","threshold_sample_size":64,"view_threshold":"1000ms"},"transactions_options":{"cleanup_config":{"cleanup_client_attempts":false,"cleanup_lost_attempts":false,"cleanup_window":"0ms","collections":[]},"durability_level":"none","query_config":{"scan_consistency":"not_bounded"},"timeout":"0ns"},"trust_certificate":"","use_ip_protocol":"any","user_agent_extra":"pycbc/4.2.1 (python/3.12.2)","view_timeout":"75000ms"}}
[2024-04-30 17:08:33.921]    0ms [debu] [42695,2096290] Query DNS-SRV: address="cb.wrr-19l-u8l1lyvi.sandbox.nonprod-project-avengers.com", service="_couchbases", nameserver="10.100.189.12:53"
[2024-04-30 17:08:34.173]  251ms [debu] [42695,2096290] DNS UDP deadline has been reached, cancelling UDP operation and fall back to TCP, address="10.100.189.12:53"
[2024-04-30 17:08:34.175]    1ms [debu] [42695,2096290] DNS UDP read operation has got error, retrying with TCP, address="10.100.189.12:53", ec=Operation aborted.
[2024-04-30 17:08:34.425]  250ms [debu] [42695,2096290] DNS deadline has been reached, cancelling in-flight operations (tcp.is_open=true, address="10.100.189.12:53")
[2024-04-30 17:08:34.426]    0ms [debu] [42695,2096290] DNS TCP connection has been aborted, address="10.100.189.12:53", ec=Operation aborted.
[2024-04-30 17:08:34.426]    0ms [warn] [42695,2096290] failed to fetch DNS SRV records for "cb.wrr-19l-u8l1lyvi.sandbox.nonprod-project-avengers.com" (Operation aborted.), assuming that cluster is listening this address
[2024-04-30 17:08:34.427]    0ms [debu] [42695,2096290] PYCBC: create conn callback completed
2024-04-30 17:08:34.427 Uncaught app exception
Traceback (most recent call last):
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo/chat_with_pdf.py", line 133, in <module>
    cluster = connect_to_couchbase(DB_CONN_STR, DB_USERNAME, DB_PASSWORD)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 168, in wrapper
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 197, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 224, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 280, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo/chat_with_pdf.py", line 76, in connect_to_couchbase
    cluster = Cluster(connect_string, options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/couchbase/cluster.py", line 101, in __init__
    self._connect()
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/couchbase/logic/wrappers.py", line 98, in wrapped_fn
    raise e
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/couchbase/logic/wrappers.py", line 82, in wrapped_fn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saurabhmishra/Desktop/work/langchain-tests/rag-demo-venv/lib/python3.12/site-packages/couchbase/cluster.py", line 107, in _connect
    raise ErrorMapper.build_exception(ret)
couchbase.exceptions.CouchbaseException: <ec=89, category=asio.system, message=Operation aborted., C Source=/private/var/folders/7w/ftplgyn52g5c95607zxkwp4m0000gq/T/pip-install-fflpx023/couchbase_9f7fcf8031554df889893a7a0d80ae91/src/connection.cxx:202>`
